general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 9

[window]
padding.x = 4
padding.y = 4
dynamic_padding = true
resize_increments = true
decorations = "None"
opacity = 0.8

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy" }
]

[cursor]
blink_interval = 300
blink_timeout = 0

[terminal]
shell = { program = "/usr/bin/zsh", args = ["-l"] }
