general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetbrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetbrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetbrainsMono Nerd Font", style = "Italic" }
size = 9

[window]
padding.x = 4
padding.y = 4
dynamic_padding = true
resize_increments = true
decorations = "None"
opacity = 0.8

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy" }
]

[terminal]
shell = { program = "/usr/bin/bash", args = ["-l"] }
